"""Job artifact and log read helper runtime for dashboard routes."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Callable, Dict, List

from fastapi import HTTPException

from app.config import AppSettings
from app.models import JobRecord


class DashboardJobArtifactRuntime:
    """Encapsulate dashboard-side job artifact and log read helpers."""

    def __init__(
        self,
        *,
        settings: AppSettings,
        timestamped_line_pattern: Any,
        classify_command_target: Callable[[str], str],
    ) -> None:
        self.settings = settings
        self.timestamped_line_pattern = timestamped_line_pattern
        self.classify_command_target = classify_command_target

    def read_agent_md_files(self, workspace_path: Path) -> List[Dict[str, str]]:
        """Read markdown files generated by agents in the workspace."""

        if not workspace_path.exists():
            return []

        md_files: List[Dict[str, str]] = []
        md_paths: List[Path] = []
        md_paths.extend(sorted(workspace_path.glob("*.md")))
        docs_dir = workspace_path / "_docs"
        if docs_dir.exists():
            md_paths.extend(sorted(docs_dir.glob("*.md")))
        seen: set[str] = set()
        for path in md_paths:
            if not path.is_file():
                continue
            rel = str(path.relative_to(workspace_path))
            if rel in seen:
                continue
            seen.add(rel)
            try:
                content = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            md_files.append({"name": rel, "content": content})

        md_files.sort(key=lambda item: item["name"])
        return md_files

    def read_stage_md_snapshots(self, job_id: str) -> List[Dict[str, Any]]:
        """Read per-stage markdown snapshots saved by orchestrator."""

        snapshot_root = (self.settings.data_dir / "md_snapshots" / job_id).resolve()
        base_root = (self.settings.data_dir / "md_snapshots").resolve()
        if not snapshot_root.exists():
            return []
        if base_root not in snapshot_root.parents and snapshot_root != base_root:
            return []

        snapshots: List[Dict[str, Any]] = []
        for path in sorted(snapshot_root.glob("attempt_*.json")):
            if not path.is_file():
                continue
            try:
                payload = json.loads(path.read_text(encoding="utf-8", errors="replace"))
            except json.JSONDecodeError:
                continue
            if not isinstance(payload, dict):
                continue
            snapshots.append(
                {
                    "attempt": int(payload.get("attempt", 0) or 0),
                    "stage": str(payload.get("stage", "")),
                    "created_at": str(payload.get("created_at", "")),
                    "changed_files": payload.get("changed_files", []),
                    "changed_files_all": payload.get("changed_files_all", []),
                    "md_files": payload.get("md_files", []),
                    "file_snapshots": payload.get("file_snapshots", []),
                }
            )

        snapshots.sort(key=lambda item: (item.get("attempt", 0), item.get("stage", "")))
        return snapshots

    def resolve_channel_log_path(self, file_name: str, channel: str = "debug") -> Path:
        """Resolve one job log path by channel with legacy fallback for debug."""

        normalized_channel = (channel or "debug").strip().lower()
        if normalized_channel not in {"debug", "user"}:
            normalized_channel = "debug"
        logs_dir = self.settings.logs_dir.resolve()
        channel_path = (logs_dir / normalized_channel / file_name).resolve()
        legacy_path = (logs_dir / file_name).resolve()

        if logs_dir not in channel_path.parents and channel_path != logs_dir:
            raise HTTPException(status_code=400, detail="Invalid log file path.")
        if logs_dir not in legacy_path.parents and legacy_path != logs_dir:
            raise HTTPException(status_code=400, detail="Invalid legacy log file path.")

        if normalized_channel == "debug" and not channel_path.exists() and legacy_path.exists():
            return legacy_path
        return channel_path

    def parse_log_events(self, log_path: Path) -> List[Dict[str, str]]:
        """Parse log lines into timeline events with inferred speaker and receiver."""

        events: List[Dict[str, str]] = []
        raw_lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()

        last_timestamp = ""
        active_target = "shell"

        for raw_line in raw_lines:
            match = self.timestamped_line_pattern.match(raw_line)
            if not match:
                if events:
                    events[-1]["message"] += "\n" + raw_line
                continue

            timestamp = match.group("ts")
            message = match.group("msg")
            last_timestamp = timestamp

            if message.startswith("[RUN] "):
                command = message.replace("[RUN] ", "", 1)
                active_target = self.classify_command_target(command)
                events.append(
                    {
                        "timestamp": timestamp,
                        "speaker": "agenthub",
                        "receiver": active_target,
                        "kind": "run",
                        "message": command,
                    }
                )
                continue

            if message.startswith("[STDOUT]"):
                events.append(
                    {
                        "timestamp": timestamp,
                        "speaker": active_target,
                        "receiver": "agenthub",
                        "kind": "stdout",
                        "message": message.replace("[STDOUT]", "", 1).strip() or "(stdout)",
                    }
                )
                continue

            if message.startswith("[STDERR]"):
                events.append(
                    {
                        "timestamp": timestamp,
                        "speaker": active_target,
                        "receiver": "agenthub",
                        "kind": "stderr",
                        "message": message.replace("[STDERR]", "", 1).strip() or "(stderr)",
                    }
                )
                continue

            if message.startswith("[STAGE] "):
                events.append(
                    {
                        "timestamp": timestamp,
                        "speaker": "agenthub",
                        "receiver": "dashboard",
                        "kind": "stage",
                        "message": message.replace("[STAGE] ", "", 1),
                    }
                )
                continue

            if message.startswith("[DONE]"):
                events.append(
                    {
                        "timestamp": timestamp,
                        "speaker": active_target,
                        "receiver": "agenthub",
                        "kind": "done",
                        "message": message,
                    }
                )
                continue

            events.append(
                {
                    "timestamp": last_timestamp,
                    "speaker": "agenthub",
                    "receiver": "dashboard",
                    "kind": "info",
                    "message": message,
                }
            )
        return events[-300:]

    @staticmethod
    def tail_text_lines(path: Path, max_lines: int = 16) -> List[str]:
        """Read the tail lines of a UTF-8 text file safely."""

        try:
            rows = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            return ["(failed to read log file)"]
        tail = rows[-max_lines:] if len(rows) > max_lines else rows
        return [row[:300] for row in tail]

    def build_focus_job_log_context(self, job: JobRecord) -> str:
        """Build detailed context for one specific job log analysis."""

        lines: List[str] = [
            "Focused job:",
            (
                f"- job_id={job.job_id} status={job.status} stage={job.stage} "
                f"app={job.app_code} track={job.track} attempt={job.attempt}/{job.max_attempts}"
            ),
            f"- issue=#{job.issue_number} title={job.issue_title}",
            f"- error={job.error_message or '-'}",
        ]

        for channel in ("debug", "user"):
            log_path = self.resolve_channel_log_path(job.log_file, channel=channel)
            if not log_path.exists():
                continue
            lines.append(f"{channel} log tail ({log_path.name}):")
            for row in self.tail_text_lines(log_path, max_lines=120):
                lines.append(f"  {row}")
        text = "\n".join(lines).strip()
        if len(text) > 20000:
            return text[:20000] + "\n...(truncated)"
        return text
